baseURL = "https://phil413.github.io/"
languageCode = "zh-cn"
title = "Fennel's blog"
theme = "github-style"
[params]
  author = "Fennel"
  description = "Love Game, Love Code, Love Life"
  github = "Phil413"
  email = "845552092@qq.com"
  url = "https://phil413.github.io/"
  favicon = "/images/favicon.ico"
  location = "China"
  lastmod = true
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]