baseURL = "https://phil413.github.io/"
languageCode = "zh-cn"
title = "Fennel's blog"
theme = "github-style"
[params]
  author = "Fennel"
  description = "天天打游戏"
  github = "Phil413"
  email = "845552092@qq.com"
  url = "https://phil413.github.io/"
  keywords = "blog, 代码, 生活"
  favicon = "/images/github.png"
  location = "China"
  lastmod = true
[[params.links]]
    title = "Link"
    href = "https://github.com/Phil413"
[[params.links]]
  title = "Link2"
  href = "https://phil413.github.io/"
  icon = "https://phil413.github.io/images/avatar.png"
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]